schemaBasePath: ./jsonschema/
schemaBaseUris:
  - ./jsonschema/
  # Look in primary schema repository for $ref fragments.
  - https://schema.wikimedia.org/repositories/primary/jsonschema/
logLevel: info
