schemaBasePath: ./jsonschema/
schemaBaseUris:
  - ./jsonschema/
  # TODO: Use schema.wikimedia.org once it is available. https://phabricator.wikimedia.org/T233630
  - https://gerrit.wikimedia.org/r/plugins/gitiles/schemas/event/primary/+/master/jsonschema/
logLevel: info
