schemaBasePath: ./jsonschema/
schemaBaseUris:
  - ./jsonschema/
  # TODO: Use schema.wikimedia.org once it is available. https://phabricator.wikimedia.org/T233630
  - https://schema.wikimedia.org/repositories/primary/jsonschema/
logLevel: info
